package Telas;


public class GerCarros extends javax.swing.JFrame {

    /**
     * Creates new form GerCarros
     */
    public GerCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jb1_Visualizar = new javax.swing.JButton();
        jb1_Adicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jb1_Visualizar.setText("Visualizar");
        jb1_Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1_VisualizarActionPerformed(evt);
            }
        });
        jPanel3.add(jb1_Visualizar);

        jb1_Adicionar.setText("Adicionar");
        jb1_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1_AdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(jb1_Adicionar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb1_VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1_VisualizarActionPerformed
        new Visualizar(this);
    }//GEN-LAST:event_jb1_VisualizarActionPerformed

    private void jb1_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1_AdicionarActionPerformed
        new Cadastro(this);
    }//GEN-LAST:event_jb1_AdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb1_Adicionar;
    private javax.swing.JButton jb1_Visualizar;
    // End of variables declaration//GEN-END:variables
}
