
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class NewJFrame extends javax.swing.JFrame {
    ArrayList<String> vNumero = new ArrayList<>();
    int decimal = -1;
    
    Character signal = ' ';
    
    Float operando = null;    
    Character operador = null;
    
    Float getVNum(){
        String nova = this.signal+String.join("", this.vNumero);
        return Float.parseFloat(nova);
    }
    
    void updateDisplay(){
        if (this.vNumero.size() > 0){
            String nova = String.join("", this.vNumero);
            this.actual.setText(this.signal+nova);
        }
        else if (this.operando != null) {            
            this.actual.setText(String.valueOf(this.operando));
        }
        else {
            this.actual.setText(this.signal+" ");
        }
        if (this.operador != null) this.selOperator.setText(String.valueOf(this.operador));
        else this.selOperator.setText("");
    }
    
    void appendNumber(Character numChar) {
        if (this.decimal < 0) {
            //maior numero inteiro tem 9 digitos
            if (this.vNumero.size() >= 9) return;
        }
        else {
            //maior decimal tem 7 digitos
            if (this.vNumero.size() - decimal - 1 >= 7) return;
        }
        
        this.vNumero.add(String.valueOf(numChar));
        this.updateDisplay();
    }
    
    void swSignal() {
        if (this.signal == '-') this.signal = ' ';
        else this.signal = '-';
        this.updateDisplay();
    }
    
    void appendDecimal(){
        if (this.decimal < 0 && this.vNumero.size() > 0) {
            this.decimal = this.vNumero.size();
            this.vNumero.add(".");
            this.updateDisplay();
        }
    }
    
    void operar(Character op) {
        
        if (this.vNumero.size() < 1) {
            this.operador = op;
            this.updateDisplay();
            return;
        } //nao fazer nada até que tenha um operando

        final Float secndOperando = getVNum();
        
        //se ainda não foi setado nenhum operando, sete-o.
        if (this.operando == null) {
            this.operando = secndOperando;
            this.operador = op;
            this.clear();
        }
        else {  //se ja existir um operando, efetuar calculo.
            //TODO Tratar tipos de ops
            final Float bkOperando = this.operando;
            
            Boolean resCalc = this.calcular(secndOperando);
            if(resCalc) this.addHistorico("" + bkOperando + ' ' + this.operador + ' ' + secndOperando + " = " + this.operando);
            this.operador = op;
            this.clear();
        }
        
        this.signal = ' ';
    }
    
    void addHistorico(String str) {
        this.historico.append("\n" + str);
    }
    
    void clear() {
        if (this.vNumero.size() < 1) {
            this.operando = null;
            this.operador = null;
            this.addHistorico("limpou tudo");
        }
        this.vNumero.clear();
        this.decimal = -1;
        this.updateDisplay();
    }
        
    Boolean calcular(Float secnd) {
        
        switch (this.operador) {
            case '+':
                this.operando += secnd;
                return true;
            case '-':
                this.operando -= secnd;
                return true;
            case 'X':
                this.operando *= secnd;
                return true;
            case '/':
                if (secnd == 0) return false;
                this.operando /= secnd;                
                return true;
            case '=':
                this.operando = secnd;
                return false;
            default: return false;
        }
    }
        
    
    

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        actual = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        selOperator = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        calc7 = new javax.swing.JButton();
        calc8 = new javax.swing.JButton();
        calc9 = new javax.swing.JButton();
        opDiv = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        calc4 = new javax.swing.JButton();
        calc5 = new javax.swing.JButton();
        calc6 = new javax.swing.JButton();
        opMult = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        calc1 = new javax.swing.JButton();
        calc2 = new javax.swing.JButton();
        calc3 = new javax.swing.JButton();
        opMin = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jbSwSignal = new javax.swing.JButton();
        jbDecimal = new javax.swing.JButton();
        calc0 = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        opPlus = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWeights = new double[] {1.0};
        jPanel2Layout.rowWeights = new double[] {1.0};
        jPanel2.setLayout(jPanel2Layout);

        actual.setEditable(false);
        actual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actual.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(actual, gridBagConstraints);

        jPanel8.setLayout(new java.awt.GridLayout(2, 1));

        selOperator.setEditable(false);
        selOperator.setOpaque(true);
        jPanel8.add(selOperator);

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel8.add(clear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel8, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1, 5, 5));

        calc7.setText("7");
        calc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc7ActionPerformed(evt);
            }
        });
        jPanel3.add(calc7);

        calc8.setText("8");
        calc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc8ActionPerformed(evt);
            }
        });
        jPanel3.add(calc8);

        calc9.setText("9");
        calc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc9ActionPerformed(evt);
            }
        });
        jPanel3.add(calc9);

        opDiv.setText("/");
        opDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivActionPerformed(evt);
            }
        });
        jPanel3.add(opDiv);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1, 5, 5));

        calc4.setText("4");
        calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc4ActionPerformed(evt);
            }
        });
        jPanel4.add(calc4);

        calc5.setText("5");
        calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc5ActionPerformed(evt);
            }
        });
        jPanel4.add(calc5);

        calc6.setText("6");
        calc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc6ActionPerformed(evt);
            }
        });
        jPanel4.add(calc6);

        opMult.setText("X");
        opMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultActionPerformed(evt);
            }
        });
        jPanel4.add(opMult);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 1, 5, 5));

        calc1.setText("1");
        calc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc1ActionPerformed(evt);
            }
        });
        jPanel5.add(calc1);

        calc2.setText("2");
        calc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc2ActionPerformed(evt);
            }
        });
        jPanel5.add(calc2);

        calc3.setText("3");
        calc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc3ActionPerformed(evt);
            }
        });
        jPanel5.add(calc3);

        opMin.setText("-");
        opMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMinActionPerformed(evt);
            }
        });
        jPanel5.add(opMin);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 1, 5, 5));

        jPanel9.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jbSwSignal.setBackground(new java.awt.Color(153, 102, 0));
        jbSwSignal.setForeground(new java.awt.Color(0, 0, 0));
        jbSwSignal.setText("+ / -");
        jbSwSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSwSignalActionPerformed(evt);
            }
        });
        jPanel9.add(jbSwSignal);

        jbDecimal.setBackground(new java.awt.Color(255, 153, 102));
        jbDecimal.setForeground(new java.awt.Color(0, 0, 0));
        jbDecimal.setText(".");
        jbDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDecimalActionPerformed(evt);
            }
        });
        jPanel9.add(jbDecimal);

        jPanel6.add(jPanel9);

        calc0.setText("0");
        calc0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc0ActionPerformed(evt);
            }
        });
        jPanel6.add(calc0);

        equals.setBackground(new java.awt.Color(255, 153, 51));
        equals.setForeground(new java.awt.Color(0, 0, 0));
        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        jPanel6.add(equals);

        opPlus.setBackground(new java.awt.Color(204, 51, 0));
        opPlus.setForeground(new java.awt.Color(0, 0, 0));
        opPlus.setText("+");
        opPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPlusActionPerformed(evt);
            }
        });
        jPanel6.add(opPlus);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new java.awt.BorderLayout());

        historico.setEditable(false);
        historico.setColumns(20);
        historico.setRows(5);
        jScrollPane1.setViewportView(historico);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calc0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc0ActionPerformed
        this.appendNumber('0');
    }//GEN-LAST:event_calc0ActionPerformed

    private void calc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc1ActionPerformed
        this.appendNumber('1');
    }//GEN-LAST:event_calc1ActionPerformed

    private void calc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc2ActionPerformed
        this.appendNumber('2');
    }//GEN-LAST:event_calc2ActionPerformed

    private void calc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc3ActionPerformed
        this.appendNumber('3');
    }//GEN-LAST:event_calc3ActionPerformed

    private void calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc4ActionPerformed
        this.appendNumber('4');
    }//GEN-LAST:event_calc4ActionPerformed

    private void calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc5ActionPerformed
        this.appendNumber('5');
    }//GEN-LAST:event_calc5ActionPerformed

    private void calc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc6ActionPerformed
        this.appendNumber('6');
    }//GEN-LAST:event_calc6ActionPerformed

    private void calc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc7ActionPerformed
        this.appendNumber('7');
    }//GEN-LAST:event_calc7ActionPerformed

    private void calc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc8ActionPerformed
        this.appendNumber('8');
    }//GEN-LAST:event_calc8ActionPerformed

    private void calc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc9ActionPerformed
        this.appendNumber('9');
    }//GEN-LAST:event_calc9ActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        this.operar('=');
    }//GEN-LAST:event_equalsActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.clear();
    }//GEN-LAST:event_clearActionPerformed

    private void jbDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDecimalActionPerformed
        this.appendDecimal();
    }//GEN-LAST:event_jbDecimalActionPerformed

    private void opPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPlusActionPerformed
        this.operar('+');
    }//GEN-LAST:event_opPlusActionPerformed

    private void opMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMinActionPerformed
        this.operar('-');
    }//GEN-LAST:event_opMinActionPerformed

    private void opMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultActionPerformed
        this.operar('X');
    }//GEN-LAST:event_opMultActionPerformed

    private void opDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivActionPerformed
        this.operar('/');
    }//GEN-LAST:event_opDivActionPerformed

    private void jbSwSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSwSignalActionPerformed
        this.swSignal();
    }//GEN-LAST:event_jbSwSignalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actual;
    private javax.swing.JButton calc0;
    private javax.swing.JButton calc1;
    private javax.swing.JButton calc2;
    private javax.swing.JButton calc3;
    private javax.swing.JButton calc4;
    private javax.swing.JButton calc5;
    private javax.swing.JButton calc6;
    private javax.swing.JButton calc7;
    private javax.swing.JButton calc8;
    private javax.swing.JButton calc9;
    private javax.swing.JButton clear;
    private javax.swing.JButton equals;
    private javax.swing.JTextArea historico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDecimal;
    private javax.swing.JButton jbSwSignal;
    private javax.swing.JButton opDiv;
    private javax.swing.JButton opMin;
    private javax.swing.JButton opMult;
    private javax.swing.JButton opPlus;
    private javax.swing.JTextField selOperator;
    // End of variables declaration//GEN-END:variables
}
